fix: electron locator bug
electron/electron-rebuild pull request #528
Opened 2020-12-03 21:30 UTC by chase-itay

bug the await is on nothing because the brackets [] have precedence

2020-12-03 21:32 UTC, malept requested changes
Thanks for spotting this! Can you add a regression test?

2020-12-03 21:32 UTC, malept commented on src/electron-locator.ts
> +    const electronPath = paths[0];
```suggestion
    const electronPath = (await searchForModule(process.cwd(), moduleName, projectRootPath))[0];
```

2020-12-15 06:00 UTC, malept commented
@chase-itay are you interested in finishing this PR so it can be merged?

2021-04-11 17:10 UTC, danielehrhardt approved these changes

2021-04-11 17:14 UTC, malept commented
I'm closing this PR for now, but if you would like to revive it, please rebase, add a regression test, and you should be able to reopen it.

2021-04-11 17:14 UTC, closed without merging